version: '3'
services:
  app:
    # container_name: simple_chat_app
    build: .
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_ADDRESS=db:5432
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
    networks:
      - db

  db:
    image: postgres:12.2-alpine
    # container_name: simple_chat_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   depends_on:
  #     - db
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - db
  #   restart: unless-stopped

volumes:
  db:

networks:
  db:
    driver: bridge
